name: pacman
version: '1.0'
base: core22
summary: CtrlX Pacman
description: CtrlX > World
 

confinement: strict
grade: stable
architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:

  flask-server: 
    command: bin/runserver.wrapper  
    plugs:
      - network-control
      - network-observe
      - network
      - network-bind
      - process-control
      - raw-usb
      - gsettings
      - udisks2
      - hardware-observe
      - system-observe
      - mount-observe
    daemon: simple 
    
      

parts:

  flask:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    python-packages: 
      - flask
      - requests
    source: .
    stage-packages:
      - usbutils
      - pciutils
      - v4l-utils
    build-packages:
      - python3-dev
      - python3-wheel
      - build-essential
      - python3-setuptools
  

  python-code:  
    source: ./Flask/
    plugin: dump
    organize:
      '*': bin/Flask/

  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/

  configs:
    plugin: dump
    source: ./configs
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}